name: Windows x64 Build (NCG defaults)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.4.1-ncg1). Leave blank to skip release."
        required: false
        default: ""
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/windows_build.yml"
      - "force-run.txt"

permissions:
  contents: write

env:
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  # Use the same approach as upstream CI for stable vcpkg behavior & caching
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"  # current used upstream

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10

  windows-x64:
    name: x86_64-pc-windows-msvc
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Use NCG hbb_common defaults
        shell: bash
        run: |
          git -C libs/hbb_common remote set-url origin https://github.com/NCG-Scott/hbb_common.git
          git -C libs/hbb_common fetch origin ncg-defaults
          git -C libs/hbb_common checkout ncg-defaults
          echo "hbb_common commit: $(git -C libs/hbb_common rev-parse --short HEAD)"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy,rustfmt

      - name: Setup LLVM (primary)
        id: llvm
        uses: KyleMayes/install-llvm-action@v2
        continue-on-error: true
        with:
          version: "15.0.7"
          directory: C:\llvm

      - name: Fallback: install LLVM via Chocolatey
        if: steps.llvm.outcome != 'success'
        shell: pwsh
        run: |
          choco install -y llvm --version=15.0.7
          echo "$env:ProgramFiles\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          if (!(Test-Path 'C:\llvm')) { New-Item -ItemType Junction -Path 'C:\llvm' -Target "$env:ProgramFiles\LLVM" | Out-Null }
          clang --version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Enable long paths
        run: git config --system core.longpaths true
        shell: pwsh

      # --- vcpkg: exact action RustDesk uses in their CI ---
      - name: Setup vcpkg with GitHub Actions cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      # Install the ports RustDesk needs on Windows (manifest-free, explicit)
      - name: Install vcpkg ports (static triplet)
        shell: bash
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows-static
        run: |
          set -e
          "$VCPKG_ROOT/vcpkg" install \
            libvpx:x64-windows-static \
            libyuv:x64-windows-static \
            opus:x64-windows-static \
            aom:x64-windows-static

      # Belt & suspenders: also clue Cargo about VCPKG in .cargo/config.toml
      - name: Ensure Cargo sees VCPKG env
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force .cargo | Out-Null
          @"
[env]
VCPKG_ROOT = "C:\\vcpkg"
VCPKG_DEFAULT_TRIPLET = "x64-windows-static"
"@ | Out-File .cargo\config.toml -Encoding UTF8
          Get-Content .cargo\config.toml

      - name: Build Windows (Flutter + Rust)
        shell: pwsh
        env:
          # **Critical**: make these visible to python→cargo→build.rs
          VCPKG_ROOT: C:\vcpkg
          VCPKG_DEFAULT_TRIPLET: x64-windows-static
          LIBCLANG_PATH: C:\llvm\bin
          RUST_BACKTRACE: 1
        run: |
          Write-Host "VCPKG_ROOT=$env:VCPKG_ROOT"
          if (Test-Path "$env:VCPKG_ROOT\installed\x64-windows-static\include") {
            Get-ChildItem "$env:VCPKG_ROOT\installed\x64-windows-static\include" | Select-Object -First 5
          } else {
            Write-Error "vcpkg headers missing — install step failed"
          }
          python --version
          python build.py --flutter

      - name: Build MSI
        shell: pwsh
        run: |
          msbuild .\res\msi\Package\Package.wixproj /p:Configuration=Release /p:Platform=x64
          New-Item -ItemType Directory -Force -Path .\Out | Out-Null
          Get-ChildItem res\msi\Package\bin\Release\*.msi | Copy-Item -Destination .\Out\
          if (Test-Path .\rustdesk-*.exe) { Copy-Item .\rustdesk-*.exe .\Out\ }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: Out\*

      - name: Create release (optional)
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: Out\*
          prerelease: false
