name: Windows x64 Build (NCG defaults)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.4.1-ncg1). Leave blank to skip release."
        required: false
        default: ""
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/windows_build.yml"
      - "force-run.txt"

permissions:
  contents: write

env:
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10

  windows-x64:
    name: x86_64-pc-windows-msvc
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Use NCG hbb_common defaults
        shell: bash
        run: |
          git -C libs/hbb_common remote set-url origin https://github.com/NCG-Scott/hbb_common.git
          git -C libs/hbb_common fetch origin ncg-defaults
          git -C libs/hbb_common checkout ncg-defaults
          echo "hbb_common commit: $(git -C libs/hbb_common rev-parse --short HEAD)"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy,rustfmt

      - name: Setup LLVM (primary)
        id: llvm
        uses: KyleMayes/install-llvm-action@v2
        continue-on-error: true
        with:
          version: "15.0.7"
          directory: C:\llvm

      - name: "Fallback: install LLVM via Chocolatey"
        if: ${{ steps.llvm.outcome != 'success' }}
        shell: pwsh
        run: |
          choco install -y llvm --version=15.0.7
          echo "$env:ProgramFiles\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          if (!(Test-Path 'C:\llvm')) { New-Item -ItemType Junction -Path 'C:\llvm' -Target "$env:ProgramFiles\LLVM" | Out-Null }
          clang --version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # ---- vcpkg: make sure *every* child process sees VCPKG_ROOT ----
      - name: Bootstrap vcpkg and install opus (Windows)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $root = "$env:GITHUB_WORKSPACE\res\vcpkg"

          if (!(Test-Path $root)) { throw "vcpkg folder missing: $root" }
          if (!(Test-Path 'C:\vcpkg')) {
            New-Item -ItemType Junction -Path 'C:\vcpkg' -Target $root | Out-Null
          }

          cd $root
          if (!(Test-Path .\vcpkg.exe)) {
            .\bootstrap-vcpkg.bat -disableMetrics
          }
          .\vcpkg.exe version
          .\vcpkg.exe install opus:x64-windows --clean-after-build

          # Export for later steps in this job
          echo "VCPKG_ROOT=C:\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "VCPKG_DEFAULT_TRIPLET=x64-windows" | Out-File -FilePath $env:GITHUB_ENV -Append
          # Also set for *new child processes* started by Python/cargo
          setx VCPKG_ROOT C:\vcpkg
          setx VCPKG_DEFAULT_TRIPLET x64-windows

      - name: Enable long paths
        run: git config --system core.longpaths true
        shell: pwsh

      - name: Build Windows (Flutter + Rust)
        shell: pwsh
        run: |
          Write-Host "VCPKG_ROOT (current proc) = $env:VCPKG_ROOT"
          if (!(Test-Path $env:VCPKG_ROOT)) { Write-Error "VCPKG_ROOT path not found" }
          python --version
          python build.py --flutter

      - name: Build MSI
        shell: pwsh
        run: |
          msbuild .\res\msi\Package\Package.wixproj /p:Configuration=Release /p:Platform=x64
          New-Item -ItemType Directory -Force -Path .\Out | Out-Null
          Get-ChildItem res\msi\Package\bin\Release\*.msi | Copy-Item -Destination .\Out\
          if (Test-Path .\rustdesk-*.exe) { Copy-Item .\rustdesk-*.exe .\Out\ }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: Out\*

      - name: Create release (optional)
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: Out\*
          prerelease: false
