name: Windows x64 Build (NCG defaults)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.4.1-ncg1). Leave blank to skip release."
        required: false
        default: ""
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/windows_build.yml"
      - "force-run.txt"

permissions:
  contents: write

env:
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10

  windows-x64:
    name: x86_64-pc-windows-msvc
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Bake in your server defaults
      - name: Use NCG hbb_common defaults
        shell: bash
        run: |
          git -C libs/hbb_common remote set-url origin https://github.com/NCG-Scott/hbb_common.git
          git -C libs/hbb_common fetch origin ncg-defaults
          git -C libs/hbb_common checkout ncg-defaults
          echo "hbb_common commit: $(git -C libs/hbb_common rev-parse --short HEAD)"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy,rustfmt

      - name: Setup LLVM (primary)
        id: llvm
        uses: KyleMayes/install-llvm-action@v2
        continue-on-error: true
        with:
          version: "15.0.7"
          directory: C:\llvm

      - name: Fallback: install LLVM via Chocolatey
        if: steps.llvm.outcome != 'success'
        shell: pwsh
        run: |
          choco install -y llvm --version=15.0.7
          echo "$env:ProgramFiles\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          if (!(Test-Path 'C:\llvm')) { New-Item -ItemType Junction -Path 'C:\llvm' -Target "$env:ProgramFiles\LLVM" | Out-Null }
          clang --version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # --- vcpkg in repo root + required ports (manifest is at vcpkg.json)
      - name: Bootstrap vcpkg and install ports
        shell: pwsh
        run: |
          $root = Join-Path $pwd.Path 'vcpkg'
          if (!(Test-Path $root)) {
            git clone --depth 1 https://github.com/microsoft/vcpkg $root
          }
          & "$root\bootstrap-vcpkg.bat" -disableMetrics
          # Export env for ALL subsequent steps (incl. cargo build scripts)
          "VCPKG_ROOT=$root" | Out-File -FilePath $env:GITHUB_ENV -Append
          "VCPKG_DEFAULT_TRIPLET=x64-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Append
          # Install the four deps RustDesk expects on Windows
          & "$root\vcpkg.exe" install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static --clean-after-build
          # (Optional) make it also visible at C:\vcpkg if anything hardcodes it
          if (!(Test-Path 'C:\vcpkg')) {
            New-Item -ItemType Junction -Path 'C:\vcpkg' -Target $root | Out-Null
          }
          & "$root\vcpkg.exe" version
          & "$root\vcpkg.exe" integrate install

      - name: Enable long paths
        run: git config --system core.longpaths true
        shell: pwsh

      - name: Build Windows (Flutter + Rust)
        shell: pwsh
        run: |
          Write-Host "VCPKG_ROOT = $env:VCPKG_ROOT"
          Write-Host "VCPKG_DEFAULT_TRIPLET = $env:VCPKG_DEFAULT_TRIPLET"
          if (!(Test-Path $env:VCPKG_ROOT)) { throw "VCPKG_ROOT not found at $env:VCPKG_ROOT" }
          python --version
          python build.py --flutter

      - name: Build MSI
        shell: pwsh
        run: |
          msbuild .\res\msi\Package\Package.wixproj /p:Configuration=Release /p:Platform=x64
          New-Item -ItemType Directory -Force -Path .\Out | Out-Null
          Get-ChildItem res\msi\Package\bin\Release\*.msi | Copy-Item -Destination .\Out\
          if (Test-Path .\rustdesk-*.exe) { Copy-Item .\rustdesk-*.exe .\Out\ }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: Out\*

      - name: Create release (optional)
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: Out\*
          prerelease: false
